Python 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:39) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
# Define the calculate_bmi function here.
# Return ONLY the result of the calculation rounded to 1 decimal place

def calculate_bmi(weight_in_pounds, height_in_inches):
...   bmi = ((weight_in_pounds) / (height_in_inches * height_in_inches)) * 703
...   return round(bmi, 1) 
... 
... height_in_inches = float(input("What is your height in inches?:"))
... weight_in_pounds = float(input("What is your weight in pounds?:"))
... 
... # Define your main() function 
... 
... def main():
...   bmi = calculate_bmi(weight_in_pounds, height_in_inches)
... 
...   if bmi <= 18.5:
...     print ("You are underweight.")
... 
...   elif 18.5< bmi <=34.9:
...     print("You are normal.")
... 
...   elif 25 <= bmi <=29.9:
...     print ("You are overweight.")
... 
...   else:
...     print("You are obese.")
... 
... 
... 
... 
... #else bmi >= 30:
... #    print ("You are Obese")
... 
... 
... 
... 
... 
... 
... 
... 
... #What goes here again?
... if __name__ == "__main__":
...   main()
